### ISSUE TITLE
How to run multiple SNI Proxy for each IP

### ISSUE THREAD

**Issue by marcusboon** [steamcache/docker-compose#1]
In the .env there is a stipulation that if we're using multiple IPs for the services we need to 

> Note, If you're using seperate IPs for each service, you may need multiple SNI Proxy containers, one on each IP.

 How do we do that?

**Comment by JasonRivers** [comment]
Thanks for picking that up, What should happen is that you run a single SNIProxy on all IPs - you won't get clashes with SNI as it's a pass-through system. I have modified the docker-compose file to listen on all IPs on a system for SNI, and removed the comment about running multiples.
